import { StyleSheet, Dimensions } from "react-native";

const { width, height } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: {
    height: height,
    width: width,
    justifyContent: "center",
    alignItems: "center",
  },
  topSearchBox: {
    display: "flex",
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    position: "absolute",
    top: 40,
    backgroundColor: "#fff",
    width: width - 20,
    padding: 10,
    zIndex: 3,
    marginTop: 10,
    borderRadius: 10,
    color: "#000",
  },
  searchDrawerMenu: {
    justifyContent: "center",
    alignItems: "center",
    width: 20,
  },
  searchInputBox: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    marginStart: 20,
    width: 200,
  },
  searchProfilebutton: {
    justifyContent: "center",
    alignItems: "center",
    width: 30,
    height: 30,
  },
  MapViewContainer: {
    position: "absolute",
    top: 0,
    zIndex: 2,
    height: 350,
    width: width,
  },
  map: {
    flex: 1,
  },
  sliderBox: {
    zIndex: 2,
    position: "absolute",
    top: 350,
  },
  sliderViewBox: {
    flex: 1,
    flexDirection: "row",
  },
  sliderbar: {
    flex: 1,
    height: 100,
    minWidth: 150,
  },
  sliderBarTouchable: {
    height: 100,
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
  },
  bottomView: {
    zIndex: 2,
    position: "absolute",
    top: 440,
    backgroundColor: "#fff",
    width: width - 5,
    height: 250,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { height: 2, width: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 0,
    borderWidth: 1,
    padding: 5,
    borderRadius: 10,
    borderColor: "#d1d1d1",
  },
  bottomViewInput: {
    backgroundColor: "#d1d1d1",
    padding: 10,
    width: width - 15,
    borderRadius: 10,
    color: "#000",
    flex: 1,
    flexDirection: "row",
  },
  bannerImage: {
    position: "absolute",
    top: 600,
    width: width,
    height: 200,
    zIndex: 0,
  },
  recentLocation: {
    borderBottomColor: "#d1d1d1",
    borderBottomWidth: 2,
    padding: 10,
    width: width - 15,
    color: "#000",
    flex: 1,
    flexDirection: "row",
  },
});
